M48
; DRILL file {KiCad 8.0.4} date 2025-03-29T15:05:09-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-29T15:05:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.810
%
G90
G05
T1
X54.24Y-134.5
X132.0Y-134.5
T2
X44.5Y-137.5
X76.5Y-48.5
X76.5Y-123.5
X163.5Y-137.5
X164.0Y-48.5
M30
